apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: anthos-commerce-cluster
  git:
    syncRepo: git@github.com:saurabhumathe/csp-config-management.git
    syncBranch: 1.0.0
    secretType: ssh
    policyDir: "hello-namespace/config-root"
