# will only be applied to clusters with belgium location label
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: commerce-user2
  annotations:
    configmanagement.gke.io/cluster-selector: selector-central-or-east
rules:
- apiGroups: [""] # core API group
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
