# will only be applied to clusters with belgium location label
kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: commerce-auditors
  annotations:
    configmanagement.gke.io/cluster-selector: selector-central-or-east
subjects:
- kind: User
  name: auditor@test.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: commerce-user
  apiGroup: rbac.authorization.k8s.io
